version: 0.2.0.{build}

configuration: Release

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

nuget:
  disable_publish_on_pr: true

before_build:
  - nuget restore

build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal

deploy:
  provider: NuGet
  api_key:
    secure: ktmOH1ucj8jtJwbg9BGa72/Rpz0vOU3qsXbZECBnPTm0pJe57u6uOWBp7nAs723x
  skip_symbols: false
  symbol_server:
  artifact: /.*\.nupkg/